### ISSUE TITLE
make failes

### ISSUE THREAD

**Issue by sap-chund** [sapcc/cyclone#7]
when running make I get this error:

```sh
gofmt -s -w cmd pkg
go vet -mod=vendor ./cmd/... ./pkg/...
build io/fs: cannot load io/fs: open /home/ccloud/cyclone/vendor/io/fs: no such file or directory
make: *** [Makefile:23: vet] Error 1
```

is there an issue in the Makefile or what am I doing wrong?

**Comment by kayrus** [comment]
@sap-chund make sure that you're using the recent golang. `io/fs` was added in `1.16`, previous golang versions don't support this.
